// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260223143102_InitialDBSchema")]
    partial class InitialDBSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Infrastructure.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("Infrastructure.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TreeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Infrastructure.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("Infrastructure.Edge", b =>
                {
                    b.HasOne("Infrastructure.Node", null)
                        .WithMany("Edges")
                        .HasForeignKey("NodeId");
                });

            modelBuilder.Entity("Infrastructure.Node", b =>
                {
                    b.HasOne("Infrastructure.Tree", null)
                        .WithMany("Nodes")
                        .HasForeignKey("TreeId");
                });

            modelBuilder.Entity("Infrastructure.Node", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("Infrastructure.Tree", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
