// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.infrastructure;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("backend.infrastructure.Entities.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TreeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Edge", b =>
                {
                    b.HasOne("backend.infrastructure.Entities.Node", null)
                        .WithMany("Edges")
                        .HasForeignKey("NodeId");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Node", b =>
                {
                    b.HasOne("backend.infrastructure.Entities.Tree", null)
                        .WithMany("Nodes")
                        .HasForeignKey("TreeId");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Node", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("backend.infrastructure.Entities.Tree", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
